spring:
  application:
    name: cozy_pets_bookings
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'FALSE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cozy_pets_bookings?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}
  sql:
    init:
      mode: never
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG

      nodeValue: WARN
    blog: WARN
server:
 port: 8081

bookings.retention.period: P365D

jwt:
  secret: ${JWT_KEY:ntPHxykAkDpPDR1K3lMEkAaWzAwP0nFSThiASB}

